site_name: Dirk Petersen's Documentation
site_url: https://dirkpetersen.github.io/docs/
repo_url: https://github.com/dirkpetersen/docs
repo_name: dirkpetersen/docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - ai-search:
      enabled: true
      mode: development

      # AWS Bedrock Configuration
      bedrock_profile: bedrock
      bedrock_region: us-west-2
      model_haiku: us.anthropic.claude-haiku-4-5-20251001-v1:0
      model_sonnet: us.anthropic.claude-sonnet-4-5-20250929-v1:0
      auto_select_model: true
      max_tokens: 4000
      temperature: 0.3
      haiku_threshold: 200000

      # Development server
      dev_server_port: 8001
      dev_server_host: localhost

      # Context options
      include_code: true
      include_navigation: true
      max_context_tokens: 900000
      exclude_patterns: []

      # UI options
      show_thinking: true
      stream_responses: true
      show_sources: true
      cache_duration: 3600
      fallback_enabled: true

nav:
  - Home: index.md
  - Shell:
      - Overview: shell/index.md
      - Basic: shell/basic/index.md
      - SSH: shell/ssh/index.md
      - Git: shell/git/index.md
      - WSL: shell/wsl/index.md
  - Code Pasting:
      - Overview: code-pasting/index.md
      - Markdown: code-pasting/markdown/index.md
      - GitHub: code-pasting/github/index.md
      - Claude Code:
          - Overview: code-pasting/claude-code/index.md
          - Tutorial: code-pasting/claude-code/tutorial.md
      - Python: code-pasting/python/index.md
  - Nvidia: nvidia/index.md
  - Clouds:
      - Overview: clouds/index.md
      - AWS: clouds/aws/index.md
      - Azure: clouds/azure/index.md
      - Google Cloud: clouds/gcp/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - toc:
      permalink: true
