site_name: Dirk Petersen's Documentation
site_url: https://dirkpetersen.github.io/docs/
repo_url: https://github.com/dirkpetersen/docs
repo_name: dirkpetersen/docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

nav:
  - Home: index.md
  - Claude Code: claude-code/index.md
  - WSL: wsl/index.md
  - AWS: aws/index.md
  - Nvidia: nvidia/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - toc:
      permalink: true
