site_name: Dirk Petersen's Documentation
site_url: https://dirkpetersen.github.io/docs/
repo_url: https://github.com/dirkpetersen/docs
repo_name: dirkpetersen/docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

nav:
  - Home: index.md
  - Shell:
      - Overview: shell/index.md
      - Basic: shell/basic/index.md
      - SSH: shell/ssh/index.md
      - Git: shell/git/index.md
      - WSL: shell/wsl/index.md
  - Code Pasting:
      - Overview: code-pasting/index.md
      - Markdown: code-pasting/markdown/index.md
      - GitHub: code-pasting/github/index.md
      - Claude Code:
          - Main: code-pasting/claude-code/index.md
          - Tutorial: code-pasting/claude-code/tutorial.md
      - Python: code-pasting/python/index.md
  - Nvidia: nvidia/index.md
  - Software: software/index.md
  - Clouds:
      - Overview: clouds/index.md
      - AWS: clouds/aws/index.md
      - Azure: clouds/azure/index.md
      - Google Cloud: clouds/gcp/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - toc:
      permalink: true
